spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: debuggeandoideas
    password: udemy
    url: dbc:postgresql://localhost:5432/web-sites
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  file:
    name: logs/logs.log
